name: Learning CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main  

jobs:
  build:
    name: Build Frontend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # ✅ Update ke v4

      - name: Install Node.js
        uses: actions/setup-node@v4  # ✅ Update ke v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run build
        run: npm run build

      - name: Upload build artifact
        uses: actions/upload-artifact@v4  # ✅ Update ke v4
        with:
          name: frontend-build
          path: frontend/dist  # Sesuaikan dengan folder output build lo
          retention-days: 1  # Artifact dihapus setelah 1 hari (opsional)

  lint:
    name: Lint Code
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # ✅ Update ke v4

      - name: Install Node.js
        uses: actions/setup-node@v4  # ✅ Update ke v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run linting
        run: npm run lint

  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # ✅ Update ke v4

      - name: Install Node.js
        uses: actions/setup-node@v4  # ✅ Update ke v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run unit tests
        run: npm run test

  deploy:
    name: Deploy to Netlify
    runs-on: ubuntu-latest
    needs: [build, lint, test] # Deploy hanya jalan kalau build, lint, dan test sukses
    defaults:
      run:
        working-directory: frontend
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # ✅ Update ke v4

      - name: Install Netlify CLI
        run: npm install -g netlify-cli

      - name: Download build artifact
        uses: actions/download-artifact@v4  # ✅ Update ke v4
        with:
          name: frontend-build
          path: frontend/dist

      - name: Deploy to Netlify
        run: netlify deploy --prod
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}