name: Learning CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main  

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run build
        run: npm run build

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: frontend-build
          path: frontend/dist
          retention-days: 1

  # lint:
  #   name: Lint Code
  #   runs-on: ubuntu-latest
  #   defaults:
  #     run:
  #       working-directory: frontend
  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v4

  #     - name: Install Node.js
  #       uses: actions/setup-node@v4
  #       with:
  #         node-version: 18

  #     - name: Install dependencies
  #       run: npm install

  #     - name: Run linting
  #       run: npm run lint

  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run unit tests
        run: npm run test --testPathIgnorePatterns="e2e"

  e2e-test:
    name: E2E Testing
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Get Netlify Deploy Preview URL
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        run: |
          echo "BASE_URL=$(curl -s -H 'Authorization: Bearer $NETLIFY_AUTH_TOKEN' \
          https://api.netlify.com/api/v1/sites/4093732d-2e58-4050-a31b-7a4dbc4de2a1/deploys | \
          jq -r 'map(select(.context=="deploy-preview")) | sort_by(.created_at) | last | .ssl_url')" >> $GITHUB_ENV

      - name: Run Playwright E2E Tests
        run: npm run test:e2e
        env:
          BASE_URL: ${{ env.BASE_URL }}